config/routes.rb
Klarwerk::Application.routes.draw do

  get "system/index"

  get "probier/probier"

  get "probier_controller/probier_view"

  get "diagramm/index"

  resources :messpunkte
  resources :einheiten

resources :diagramme do
  member do
    get 'anfangzeit'
  end
end
 
  resources :quellen
  match 'quellen/:id/aktiv_umschalten' => 'quellen#aktiv_umschalten', :as => :aktiv_umschalten
  match 'quellen/:id/generiere/:tage/:tage_zurueck' => 'quellen#generiere', :as => :werte_generieren
  
  resources :zeiten
  
  resources :diagramme
  resources :diaquen
  
  match 'diagramme/:id/showfix' => 'diagramme#showfix', :as => :showfix
  match 'diagramme/:id/ajja' => 'diagramme#ajja', :as => :ajja
  
  match 'expert_modus/:zustand' => 'expert#schalten', :as => :expert_modus
  match 'diagramme/:id/dauer/:dauer' => 'diagramme#dauer', :as => :quelle_rein
  match 'diagramme/:id/quelle_rein/:quelle_id' => 'diagramme#quelle_rein', :as => :quelle_rein
  match 'diagramme/:id/quelle_raus/:quelle_id' => 'diagramme#quelle_raus', :as => :quelle_raus
  
  match '/' => 'diagramme#index'
  
  match '/:controller(/:action(/:id))'
end
__END__
  map.resources :messpunkte
  map.resources :einheiten
  
  map.resources :quellen
  map.aktiv_umschalten 'quellen/:id/aktiv_umschalten', :controller => 'quellen', :action => 'aktiv_umschalten'
  map.werte_generieren 'quellen/:id/generiere/:tage/:tage_zurueck', :controller => 'quellen', :action => 'generiere'

  map.resources :zeiten

  map.resources :diagramme, :has_many => :diaquen  # Verschachtelt ("nested ressource")
  map.resources :diaquen  # Damit sind die diaquen auch nichtverschachtelt zugreifbar.

  map.showfix 'diagramme/:id/showfix', :controller => 'diagramme', :action => 'showfix'

  map.expert_modus 'expert_modus/:zustand', :controller => 'expert', :action => 'schalten'
  map.quelle_rein 'diagramme/:id/dauer/:dauer', :controller => 'diagramme', :action => 'dauer'
  map.quelle_rein 'diagramme/:id/quelle_rein/:quelle_id', :controller => 'diagramme', :action => 'quelle_rein'
  map.quelle_raus 'diagramme/:id/quelle_raus/:quelle_id', :controller => 'diagramme', :action => 'quelle_raus'

  map.root :controller => "diagramme", :action => "index"

  

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/controllers/zeiten_controller.rb
class ZeitenController < ApplicationController
  # GET /zeiten
  # GET /zeiten.xml
  def index
    @zeiten = Zeit.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @zeiten }
    end
  end

  # GET /zeiten/1
  # GET /zeiten/1.xml
  def show
    @zeit = Zeit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @zeit }
    end
  end

  # GET /zeiten/new
  # GET /zeiten/new.xml
  def new
    @zeit = Zeit.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @zeit }
    end
  end

  # GET /zeiten/1/edit
  def edit
    @zeit = Zeit.find(params[:id])
  end

  # POST /zeiten
  # POST /zeiten.xml
  def create
    @zeit = Zeit.new(params[:zeit])

    respond_to do |format|
      if @zeit.save
        flash[:notice] = 'Zeit was successfully created.'
        format.html { redirect_to(@zeit) }
        format.xml  { render :xml => @zeit, :status => :created, :location => @zeit }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @zeit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /zeiten/1
  # PUT /zeiten/1.xml
  def update
    @zeit = Zeit.find(params[:id])

    respond_to do |format|
      if @zeit.update_attributes(params[:zeit])
        flash[:notice] = 'Zeit was successfully updated.'
        format.html { redirect_to(@zeit) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @zeit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /zeiten/1
  # DELETE /zeiten/1.xml
  def destroy
    @zeit = Zeit.find(params[:id])
    @zeit.destroy

    respond_to do |format|
      format.html { redirect_to(zeiten_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/zeiten_helper.rb
module ZeitenHelper
end

app/views/zeiten/edit.html.erb
<h1>Editing zeit</h1>

<% form_for(@zeit) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :bis %><br />
    <%= f.datetime_select :bis %>
  </p>
  <p>
    <%= f.label :dauer %><br />
    <%= f.text_field :dauer %>
  </p>
  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @zeit %> |
<%= link_to 'Back', zeiten_path %>

app/views/zeiten/index.html.erb
<h1>Listing zeiten</h1>

<table>
  <tr>
    <th>Bis</th>
    <th>Dauer</th>
  </tr>

<% for zeit in @zeiten %>
  <tr>
    <td><%=h zeit.bis %></td>
    <td><%=h zeit.dauer %></td>
    <td><%= link_to 'Show', zeit %></td>
    <td><%= link_to 'Edit', edit_zeit_path(zeit) %></td>
    <td><%= link_to 'Destroy', zeit, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New zeit', new_zeit_path %>

app/views/zeiten/new.html.erb
<h1>New zeit</h1>

<% form_for(@zeit) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :bis %><br />
    <%= f.datetime_select :bis %>
  </p>
  <p>
    <%= f.label :dauer %><br />
    <%= f.datetime_select :dauer %>
  </p>
  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', zeiten_path %>

app/views/zeiten/show.html.erb
<p>
  <b>Bis:</b>
  <%=h @zeit.bis %>
</p>

<p>
  <b>Dauer:</b>
  <%=h @zeit.dauer %>
</p>


<%= link_to 'Edit', edit_zeit_path(@zeit) %> |
<%= link_to 'Back', zeiten_path %>