config/routes.rb
Klarwerk::Application.routes.draw do

  get "system/index"

  get "probier/probier"

  get "probier_controller/probier_view"

  get "diagramm/index"

  resources :messpunkte
  resources :einheiten

resources :diagramme do
  member do
    get 'anfangzeit'
  end
end
 
  resources :quellen
  match 'quellen/:id/aktiv_umschalten' => 'quellen#aktiv_umschalten', :as => :aktiv_umschalten
  match 'quellen/:id/generiere/:tage/:tage_zurueck' => 'quellen#generiere', :as => :werte_generieren
  
  resources :zeiten
  
  resources :diagramme
  resources :diaquen
  
  match 'diagramme/:id/showfix' => 'diagramme#showfix', :as => :showfix
  match 'diagramme/:id/ajja' => 'diagramme#ajja', :as => :ajja
  
  match 'expert_modus/:zustand' => 'expert#schalten', :as => :expert_modus
  match 'diagramme/:id/dauer/:dauer' => 'diagramme#dauer', :as => :quelle_rein
  match 'diagramme/:id/quelle_rein/:quelle_id' => 'diagramme#quelle_rein', :as => :quelle_rein
  match 'diagramme/:id/quelle_raus/:quelle_id' => 'diagramme#quelle_raus', :as => :quelle_raus
  
  match '/' => 'diagramme#index'
  
  match '/:controller(/:action(/:id))'
end
__END__
  map.resources :messpunkte
  map.resources :einheiten
  
  map.resources :quellen
  map.aktiv_umschalten 'quellen/:id/aktiv_umschalten', :controller => 'quellen', :action => 'aktiv_umschalten'
  map.werte_generieren 'quellen/:id/generiere/:tage/:tage_zurueck', :controller => 'quellen', :action => 'generiere'

  map.resources :zeiten

  map.resources :diagramme, :has_many => :diaquen  # Verschachtelt ("nested ressource")
  map.resources :diaquen  # Damit sind die diaquen auch nichtverschachtelt zugreifbar.

  map.showfix 'diagramme/:id/showfix', :controller => 'diagramme', :action => 'showfix'

  map.expert_modus 'expert_modus/:zustand', :controller => 'expert', :action => 'schalten'
  map.quelle_rein 'diagramme/:id/dauer/:dauer', :controller => 'diagramme', :action => 'dauer'
  map.quelle_rein 'diagramme/:id/quelle_rein/:quelle_id', :controller => 'diagramme', :action => 'quelle_rein'
  map.quelle_raus 'diagramme/:id/quelle_raus/:quelle_id', :controller => 'diagramme', :action => 'quelle_raus'

  map.root :controller => "diagramme", :action => "index"

  

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/controllers/quellen_controller.rb
class QuellenController < ApplicationController
  # GET /quellen
  # GET /quellen.xml
  def index
    @alle_quellen = Quelle.all
    @aktive_quellen = Quelle.alle_aktiven
    @inaktive_quellen = @alle_quellen - @aktive_quellen

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @quellen }
    end
  end

  def aktiv_umschalten
    @quelle = Quelle.find(params[:id])
    @quelle.aktiv = ! @quelle.aktiv
    @quelle.save!
    redirect_to :action => 'index'
  end

  # GET /quellen/1
  # GET /quellen/1.xml
  def show
    @quelle = Quelle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @quelle }
    end
  end

  # GET /quellen/new
  # GET /quellen/new.xml
  def new
    @quelle = Quelle.new
    @quelle.aktiv = true

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @quelle }
    end
  end

  # GET /quellen/1/edit
  def edit
    @quelle = Quelle.find(params[:id])
  end

  # POST /quellen
  # POST /quellen.xml
  def create
    @quelle = Quelle.new(params[:quelle])

    respond_to do |format|
      if @quelle.save
        flash[:notice] = 'Messgr&ouml;&szlig;e wurde gespeichert.'
        format.html { redirect_to(quellen_path) }
        format.xml  { render :xml => @quelle, :status => :created, :location => @quelle }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @quelle.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /quellen/1
  # PUT /quellen/1.xml
  def update
    @quelle = Quelle.find(params[:id])

    respond_to do |format|
      if @quelle.update_attributes(params[:quelle])
        flash[:notice] = 'Messgr&ouml;&szlig;e wurde gespeichert'
        format.html { redirect_to(quellen_path) } #@quelle) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @quelle.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /quellen/1
  # DELETE /quellen/1.xml
  def destroy
    @quelle = Quelle.find(params[:id])
    @quelle.destroy

    respond_to do |format|
      format.html { redirect_to(quellen_url) }
      format.xml  { head :ok }
    end
  end


  def generiere
    @quelle = Quelle.find(params[:id])
    zeitraum = Zeit.new
    zeitraum.dauer = params[:tage].to_i.days
    if zeitraum.dauer == 0
      return redirect_to :action => "index"
    end
    zeitraum.bis = Time.now - params[:tage_zurueck].to_i.days if params[:tage_zurueck]
    @quelle.generiere_zufaellig(zeitraum)
    redirect_to :controller => "messpunkte", :action => "index"
  end

end

app/helpers/quellen_helper.rb
module QuellenHelper
end

app/views/quellen/_haupt_form.html.erb
<%= javascript_include_tag :defaults %>

<%= javascript_include_tag 'picky_color' %>
<%= stylesheet_link_tag 'picky_color' %>

<%= simple_form_for(@quelle) do |f| %>
<% if @quelle.errors.full_messages != []%>
  <%= @quelle.errors.full_messages %>
  <% end %>

<script type="text/javascript">
//  $ -> $('input[type=text]').minicolors()  
</script>
  
<table  class="listenkopf">
  <tr><td>
    <%= f.label :adresse %></td><td>
    <%= f.text_field :adresse %>
  </td></tr>
  <tr><td>
    <%= f.label :name %></td><td>
    <%= f.text_field :name %>
  </td></tr>
  <tr><td>
    <%= f.label :farbe %></td><td>
    <!--%= f.input :farbe, collection: {green: '#7bd148',  bold_blue:  '#5484ed'}, selected: '#7bd148' %-->
    <%= f.input :farbe_mit_raute, as: :minicolors, label: '.' %>
    <!--%= f.minicolors :farbe_mit_raute %-->
    <!--%= raw(f.picky_color :farbe, :size => 6) %-->
  </td></tr>
  <tr><td>
    <%= f.label :variablen_art %></td><td>
    <%= f.text_field :variablen_art %>
  </td></tr>
  <tr><td>
    <%= f.label :Beschreibung %></td><td>
    <%= f.text_field :beschreibung %>
  </td></tr>
  <tr><td>
    <% einheiten_auswahl = Einheit.find(:all).map {|einheit| [einheit.name, einheit.id]}  %>
    <%= f.label :einheit %></td><td>
    <%= f.select("einheit_id", einheiten_auswahl) %>
  </td></tr>
  <tr><td>
    <%= f.label :aktiv %></td><td>
    <%= f.check_box :aktiv %>
  </td></tr>
</table>
  <P><%= f.submit knopf_text %></P>
    
<% end %>

<%= link_to raw('Zur&uuml;ck zur Messgr&ouml;&szlig;enliste'), quellen_path %>

app/views/quellen/edit.html.erb
<% einheiten_auswahl = Einheit.find(:all).map do |e| [e.name, e.id] end.sort %>
<h1>Messgr&ouml;&szlig;e bearbeiten</h1>



<%= render :partial => "haupt_form", :locals => {:knopf_text => "Speichern"} %>

app/views/quellen/index.html.erb
<h1 style="text-align: center;">Messgr&ouml;&szlig;en <i class="material-icons medium">input</i></h1>

<TABLE class="striped">
  <thead>
    <tr class="listenkopf">
      <th>Adresse</th>
      <th>Name</th>
      <th>Typ</th>
      <th>Einheit</th>
      <th>Aktiv</th>
      <th></th>
      <th></th>
      <th>Beschreibung</th>
    </tr>
  </thead>
<% [@aktive_quellen, @inaktive_quellen].each do |quellen_array| %>
  <% for quelle in quellen_array %>
    <tr  class="<%= cycle('', 'un') + 'gerade'%>">
      <%  if quelle %>
      <td><%=h quelle.adresse %></td>
      <td><font color="#<%=quelle.farbe%>"><%=h quelle.name %></font></td>
      <td><%=h quelle.variablen_art %></td>
      <td><%=h quelle.einheit && quelle.einheit.name %></td>
      <td><%=h quelle.aktiv ? "ja" : "nein" %></td>
      <td><%= link_to (quelle.aktiv ? "de" : "")+"aktivieren", aktiv_umschalten_path(quelle.id) %></td>
      <td><%= link_to 'bearbeiten', edit_quelle_path(quelle) %></td>
      <td><%=h quelle.beschreibung %></td>
      <% end %>
    </tr>
  <% end %>
  <tr><td colspan=9><hr size=3></td></tr>
<% end %>
</table>

<br />

<%= link_to raw('Neue Messgr&ouml;&szlig;e'), new_quelle_path %>

app/views/quellen/new.html.erb

<h1>Neue Messgr&ouml;&szlig;e</h1>




<%= render :partial => "haupt_form", :locals => {:knopf_text => "Erstellen"} %>


app/views/quellen/show.html.erb
<p>
  <b>Adresse:</b>
  <%=h @quelle.adresse %>
</p>

<p>
  <b>Name:</b>
  <%=h @quelle.name %>
</p>

<p>
  <b>Typ:</b>
  <%=h @quelle.variablen_art %>
</p>

<p>
  <b>Beschreibung:</b>
  <%=h @quelle.beschreibung %>
</p>

<p>
  <b>Einheit:</b>
  <%=h @quelle.einheit ? @quelle.einheit.name : "--" %>
</p>

<p>
  <b>Aktiv:</b>
  <!--%=h @quelle.status %-->
  <%=h @quelle.aktiv ? "ja" : "nein" %>
</p>


<%= link_to 'Bearbeiten', edit_quelle_path(@quelle) %> |
<%= link_to 'Liste', quellen_path %>