config/routes.rb
Klarwerk::Application.routes.draw do

  get "system/index"

  get "probier/probier"

  get "probier_controller/probier_view"

  get "diagramm/index"

  resources :messpunkte
  resources :einheiten

resources :diagramme do
  member do
    get 'anfangzeit'
  end
end
 
  resources :quellen
  match 'quellen/:id/aktiv_umschalten' => 'quellen#aktiv_umschalten', :as => :aktiv_umschalten
  match 'quellen/:id/generiere/:tage/:tage_zurueck' => 'quellen#generiere', :as => :werte_generieren
  
  resources :zeiten
  
  resources :diagramme
  resources :diaquen
  
  match 'diagramme/:id/showfix' => 'diagramme#showfix', :as => :showfix
  match 'diagramme/:id/ajja' => 'diagramme#ajja', :as => :ajja
  
  match 'expert_modus/:zustand' => 'expert#schalten', :as => :expert_modus
  match 'diagramme/:id/dauer/:dauer' => 'diagramme#dauer', :as => :quelle_rein
  match 'diagramme/:id/quelle_rein/:quelle_id' => 'diagramme#quelle_rein', :as => :quelle_rein
  match 'diagramme/:id/quelle_raus/:quelle_id' => 'diagramme#quelle_raus', :as => :quelle_raus
  
  match '/' => 'diagramme#index'
  
  match '/:controller(/:action(/:id))'
end
__END__
  map.resources :messpunkte
  map.resources :einheiten
  
  map.resources :quellen
  map.aktiv_umschalten 'quellen/:id/aktiv_umschalten', :controller => 'quellen', :action => 'aktiv_umschalten'
  map.werte_generieren 'quellen/:id/generiere/:tage/:tage_zurueck', :controller => 'quellen', :action => 'generiere'

  map.resources :zeiten

  map.resources :diagramme, :has_many => :diaquen  # Verschachtelt ("nested ressource")
  map.resources :diaquen  # Damit sind die diaquen auch nichtverschachtelt zugreifbar.

  map.showfix 'diagramme/:id/showfix', :controller => 'diagramme', :action => 'showfix'

  map.expert_modus 'expert_modus/:zustand', :controller => 'expert', :action => 'schalten'
  map.quelle_rein 'diagramme/:id/dauer/:dauer', :controller => 'diagramme', :action => 'dauer'
  map.quelle_rein 'diagramme/:id/quelle_rein/:quelle_id', :controller => 'diagramme', :action => 'quelle_rein'
  map.quelle_raus 'diagramme/:id/quelle_raus/:quelle_id', :controller => 'diagramme', :action => 'quelle_raus'

  map.root :controller => "diagramme", :action => "index"

  

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/controllers/messpunkte_controller.rb
class MesspunkteController < ApplicationController
  # GET /messpunkte
  # GET /messpunkte.xml
  def index
    @messpunkte = Messpunkt.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @messpunkte }
    end
  end

  # GET /messpunkte/1
  # GET /messpunkte/1.xml
  def show
    @messpunkt = Messpunkt.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @messpunkt }
    end
  end

  # GET /messpunkte/new
  # GET /messpunkte/new.xml
  def new
    @messpunkt = Messpunkt.new
    @akt_quelle_id = session[:akt_quelle_id]
    @alle_quellen = Quelle.alle_aktiven.collect {|q| [ q.name, q.id ] }
    if @akt_quelle_id.nil? then @akt_quelle_id = @alle_quellen.first.last end
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @messpunkt }
    end
  end

  # GET /messpunkte/1/edit
  def edit
    @messpunkt = Messpunkt.find(params[:id])
  end

  # POST /messpunkte
  # POST /messpunkte.xml
  def create
    @messpunkt = Messpunkt.new(params[:messpunkt])
    session[:akt_quelle_id] = @messpunkt.quelle_id
    
    respond_to do |format|
      if @messpunkt.save
        flash[:notice] = 'Messpunkt was successfully created.'
        format.html { redirect_to(:action => "index") }
        format.xml  { render :xml => @messpunkt, :status => :created, :location => @messpunkt }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @messpunkt.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /messpunkte/1
  # PUT /messpunkte/1.xml
  def update
    @messpunkt = Messpunkt.find(params[:id])

    respond_to do |format|
      if @messpunkt.update_attributes(params[:messpunkt])
        flash[:notice] = 'Messpunkt was successfully updated.'
        format.html { redirect_to(@messpunkt) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @messpunkt.errors, :status => :unprocessable_entity }
      end
    end
  end
  def test
    Quellen.all.each do |quelle|
      zeitraum = Zeit.new 
      zeitraum.finde_oder_neu(Time.now, 1.min)
      messpunkte = Messpunkt.finde_fuer_quelle_und_zeit(quelle, zeitraum)
      p "messpunkte"
      #messpunkte << Messpunkt.where(:quelle_id => quelle.id).last
      #for(i = 0; i < 10; i++) do 
      #  if Messpunkt.where(:quelle_id => quelle.id )[i]
      #end 
    end  
  end   

  # DELETE /messpunkte/1
  # Test
  # DELETE /messpunkte/1.xml
  def destroy
    @messpunkt = Messpunkt.find(params[:id])
    @messpunkt.destroy

    respond_to do |format|
      format.html { redirect_to(messpunkte_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/messpunkte_helper.rb
module MesspunkteHelper
end

app/views/messpunkte/edit.html.erb
<h1>Editing messpunkt</h1>

<% form_for(@messpunkt) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :zeit %><br />
    <%= f.datetime_select :zeit %>
  </p>
  <p>
    <%= f.label :wert %><br />
    <%= f.text_field :wert %>
  </p>
  <p>
    <%= f.label :quelle_id %><br />
    <%= f.text_field :quelle_id %>
  </p>
  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @messpunkt %> |
<%= link_to 'Back', messpunkte_path %>

app/views/messpunkte/index.html.erb
<h1>Listing messpunkte</h1>

<table>
  <tr>
    <th>Zeit</th>
    <th>Wert</th>
    <th>Messgröße</th>
  </tr>

<% for messpunkt in @messpunkte %>
  <tr>
    <td><%=h messpunkt.zeit %></td>
    <td><%=h messpunkt.wert %></td>
    <td><%=h messpunkt.quelle_id %></td>
    <td><%= link_to 'Show', messpunkt %></td>
    <td><%= link_to 'Edit', edit_messpunkt_path(messpunkt) %></td>
    <td><%= link_to 'Destroy', messpunkt, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New messpunkt', new_messpunkt_path %>

app/views/messpunkte/new.html.erb
<h1>New messpunkt</h1>

<% form_for(@messpunkt) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :zeit %><br />
    <%= f.datetime_select :zeit %>
  </p>
  <p>
    <%= f.label :wert %><br />
    <%= f.text_field :wert, :value => rand(100) %>
  </p>
  <p>
    <%= f.label :quelle_id %><br />
    <%= f.select :quelle_id, @alle_quellen, :selected => @akt_quelle_id %>
  </p>
  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', messpunkte_path %>

app/views/messpunkte/show.html.erb
<p>
  <b>Zeit:</b>
  <%=h @messpunkt.zeit %>
</p>

<p>
  <b>Wert:</b>
  <%=h @messpunkt.wert %>
</p>

<p>
  <b>Diagramm:</b>
  <%=h @messpunkt.quelle_id %>
</p>


<%= link_to 'Edit', edit_messpunkt_path(@messpunkt) %> |
<%= link_to 'Back', messpunkte_path %>