config/routes.rb
Klarwerk::Application.routes.draw do

  get "system/index"

  get "probier/probier"

  get "probier_controller/probier_view"

  get "diagramm/index"

  resources :messpunkte
  resources :einheiten

resources :diagramme do
  member do
    get 'anfangzeit'
  end
end
 
  resources :quellen
  match 'quellen/:id/aktiv_umschalten' => 'quellen#aktiv_umschalten', :as => :aktiv_umschalten
  match 'quellen/:id/generiere/:tage/:tage_zurueck' => 'quellen#generiere', :as => :werte_generieren
  
  resources :zeiten
  
  resources :diagramme
  resources :diaquen
  
  match 'diagramme/:id/showfix' => 'diagramme#showfix', :as => :showfix
  match 'diagramme/:id/ajja' => 'diagramme#ajja', :as => :ajja
  
  match 'expert_modus/:zustand' => 'expert#schalten', :as => :expert_modus
  match 'diagramme/:id/dauer/:dauer' => 'diagramme#dauer', :as => :quelle_rein
  match 'diagramme/:id/quelle_rein/:quelle_id' => 'diagramme#quelle_rein', :as => :quelle_rein
  match 'diagramme/:id/quelle_raus/:quelle_id' => 'diagramme#quelle_raus', :as => :quelle_raus
  
  match '/' => 'diagramme#index'
  
  match '/:controller(/:action(/:id))'
end
__END__
  map.resources :messpunkte
  map.resources :einheiten
  
  map.resources :quellen
  map.aktiv_umschalten 'quellen/:id/aktiv_umschalten', :controller => 'quellen', :action => 'aktiv_umschalten'
  map.werte_generieren 'quellen/:id/generiere/:tage/:tage_zurueck', :controller => 'quellen', :action => 'generiere'

  map.resources :zeiten

  map.resources :diagramme, :has_many => :diaquen  # Verschachtelt ("nested ressource")
  map.resources :diaquen  # Damit sind die diaquen auch nichtverschachtelt zugreifbar.

  map.showfix 'diagramme/:id/showfix', :controller => 'diagramme', :action => 'showfix'

  map.expert_modus 'expert_modus/:zustand', :controller => 'expert', :action => 'schalten'
  map.quelle_rein 'diagramme/:id/dauer/:dauer', :controller => 'diagramme', :action => 'dauer'
  map.quelle_rein 'diagramme/:id/quelle_rein/:quelle_id', :controller => 'diagramme', :action => 'quelle_rein'
  map.quelle_raus 'diagramme/:id/quelle_raus/:quelle_id', :controller => 'diagramme', :action => 'quelle_raus'

  map.root :controller => "diagramme", :action => "index"

  

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/helpers/diagramme_helper.rb
module DiagrammeHelper

  def navigations_dauern(akt_zeit)
    anzahl_weiter = 3
    laenger = (1..anzahl_weiter).inject([akt_zeit]) {|zeiten, idx| [zeiten.first.laenger] + zeiten}
    kuerzer = (1..anzahl_weiter).inject([akt_zeit]) {|zeiten, idx| zeiten + [zeiten.last.kuerzer]}
    dauern = (laenger + [akt_zeit] + kuerzer).map(&:dauer)
    dauern += [1.weeks, 12.hours]
    dauern = dauern.uniq.sort.reverse
    dauern += [nil] if dauern.size < 2 * anzahl_weiter + 1 + 2
    dauern
  end
end

app/views/diagramme/_aktuelle_zeit.html.erb
<%#
# encoding: utf-8

# To change this template, choose Tools | Templates
%>
<div id="aktuelle_zeit">
  <TABLE width="100%">
    <TR>
      <TD align="center">

      <!--TD width="25%"  valign="top" align="center"-->
        <!--%= link_to_remote image_tag("lupeminusgif3.png", :alt => 'Auschnitt verkleinern',  :class => "navi_button"), :url => url_for({ :action => "zoom_out", :id => params[:id], :format => "js" }) %-->
        <!--%= link_to_remote image_tag("lupeplusgif3.png", :alt => 'Auschnitt vergrößern',  :class => "navi_button"), :url => url_for({ :action => "zoom_in", :id => params[:id], :format => "js" }) %-->
        <!--%= @chart.link_to_remote_ofc_load image_tag("lupeplusgif3.png",  :alt => 'Auschnitt vergrößern'),  "my_chart_js_1", url_for({ :action => "zoom_in", :id => params[:id], :format => "json" }) %-->
        <% dauern = navigations_dauern(session[:akt_zeit]) %>
        <% dauern.each do |dauer| %>

          <% if session[:akt_zeit].dauer == dauer then %>
            <font size="+2"> &nbsp; <%= session[:akt_zeit].lesbar %> &nbsp; </font>
          <% elsif dauer.nil? then %>
            &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
          <% else %>
            &nbsp; <%= link_to dauer_lesbar(dauer), url_for({ :action => "dauer", :id => params[:id], :dauer => dauer, :format => "js" }), :remote=>true %> &nbsp;
          <% end %>
        <% end %>
        
      </TD>
      </TD>
      <TD valign="top" width="10%" align="right">
      </TD>
      <TD  valign="top" width="8%"  align="left">
        <%= link_to raw("<div style='text-align: center;'><i class='fa fa-fast-backward fa-4x'></i><br>Anfangszeit</div>"),
         url_for(action: "verschieben", anfang: "anfang", id: params[:id], format: "js"), :remote=>true %> 
      </TD>
      <TD  valign="top" width="7%"  align="center">
        <%= link_to raw("<div style='text-align: center;'><i class='fa fa-long-arrow-left fa-4x'></i><br>Zurück</div>"), 
                    url_for(action: "verschieben", anfang: "links", id: params[:id], format: "js"), :remote=>true %> 
        <!--edit_kurve_path(@kurve) % | -->
        <!--%= @chart.link_to_remote_ofc_load image_tag("arrow_left3.png",  :class => "gruenlink"), "my_chart_js_1", url_for({ :action => "links", :id => params[:id], :format => "json" }) %--> <!--edit_kurve_path(@kurve) % | -->
     </TD>
     <TD>
        <%= link_to raw("<div style='text-align: center;'><i class='fa fa-long-arrow-right fa-4x'></i><br>Vorwärts</div>"),
                    url_for(:action => "verschieben", anfang: "rechts", :id => params[:id], :format => "js"), :remote=>true %>
      </TD>
      <TD WIDTH="2%"></TD>
      <TD WIDTH="7%">
      	<%= link_to raw("<div style='text-align: center;'><i class='fa fa-fast-forward fa-4x'></i><br>Aktuelle Zeit</div>"),
      	 url_for(action: "verschieben", anfang: "aktuell", id: params[:id], format: "js"), :remote=>true %> 
      </TD>
    </TR>
  </TABLE>
</div>
<!--div id="kurz_debug_div"/-->

app/views/diagramme/_grafik.html.erb
<div id="grafik_bereich">
    <% #line_chart ajja_path %>
    <hr>
    <%= high_chart("div_diagramm", @highchart)%>
    <hr>
  <!--%= @graph %-->
 

    <% #@chart.js_open_flash_chart_object("my_chart_js_1", "100%", 800) %>

    <script type="text/javascript">
      function reload_chart() {

      tmp_= findSWF("my_chart_js_1");
      new Ajax.Request('<%= url_for(:action => "show", :id => params[:id], :format => "json") %>', {
        method    : 'get',
        onSuccess : function(obj) {tmp_.load(obj.responseText);},
        onFailure : function(obj) {alert("Nachladen funktionierte nicht");}});
      }
    </script>
</div>
  <%= render :partial => "aktuelle_zeit" %>
<script type="text/javascript">
  function highchart_anpassung(){
    height = $(window).height() / 100 * 70;
    width = $(window).width();
    chart_div_diagramm.setSize(width, height);
  }
  $(window).resize(highchart_anpassung);
  $(window).load(highchart_anpassung);
</script>

app/views/diagramme/_quellen_auswahl_listen.html.erb
<%=  simple_fields_for @diagramm do |f| %>
  <div class="row">
    <div class="col s6">  
        <div id="Quellentabelle" style="height:300px; overflow:auto;">
        <table class="striped">
            <% @freie_quellen.each do |quelle| %>
              <tr><td> 
                <font color="#<%=  quelle.farbe %>"><%=h quelle.name %></font>
              </td><td>
                  <%= link_to raw("<i class='fa fa-long-arrow-right fa-2x'></i>"),
                              quelle_rein_path(@diagramm.id, quelle.id), 
                              :remote=>true, 
                              :"data-replace" => "#quellen_auswahl_listen" %>
              </td></tr>
          <% end %>
        </table>
      </div>
    </div>
    <div class="col s6">  
      <div id="Quellentabelle">
        <table class="striped">
          <% nummer = -1 %>
          <% @ausgewaehlte_diaquen.each do |diaque| %>
            <%= f.simple_fields_for :diaquen,  diaque do |diaque_f| %>
              <tr><td>
                <%= link_to raw("<i class='fa fa-long-arrow-left fa-2x'></i>"),
                            quelle_raus_path(@diagramm.id, diaque.quelle_id), 
                            :remote=>true, 
                            :"data-replace" => "#quellen_auswahl_listen" %>
              </td><td>
                <%= diaque_f.input :farbe_mit_raute, as: :minicolors, :size => 6, :default => diaque.anzuzeigende_farbe %>
              </td><td>
                <font color="#<%= diaque.anzuzeigende_farbe %>"> <%=h diaque.quelle.name %> </font>
              </td></tr>
            <% end %>
          <% end %>
          <% nummer = -1 %>
          <% @ausgewaehlte_diaquen.each do |diaque| %>
            <%= f.simple_fields_for :diaquen,  diaque do |diaque_f| %>
              <script type="text/javascript">
                try {
                  $('#minicolors_debug_div').prepend("<%= nummer += 1 %>");
                  $('#diagramm_diaquen_attributes_<%= nummer %>_farbe_mit_raute').minicolors({
                  //$('input[data-minicolors]').minicolors({
                    change: function(hex, opacity) {
                        $("#minicolors_debug_div").prepend(hex + " - <%= diaque.id%> - <%=diaque.farbe%> <br>");
                        //console.log(hex + ' - ' + opacity);
                        var farbe = hex.replace("#", ""); // Probleme mit Raute bei Übergabe als Parameter in Rails 
                        var link = '<%= url_for({ :controller => "diaquen", :action => "ajax_update", :id => diaque}) %>';
                        link = link + '?farbe=' + farbe;
                         $.ajax({
                          type:   'POST',
                          url:    link,
                          async:  true
                        });
                    },
                    changeDelay: 44
                  });
                } catch(e) {
                  alert(e);
                  $("#fehlerausgabe_div").html("Fehler beim Farbe aktualisieren: <b>" + e + "</b>");
                }
              </script>
            <% end %>
          <% end %>
        </table>
      </div>
    </div>
<% end %>
<script type="text/javascript">
      var link = '<%= url_for({:controller => "diagramme", :action => "render_chart_update", :id => @diagramm.id}) %>';
      $.post(link);
</script>

app/views/diagramme/_quellen_selektor.html.erb
<%= javascript_include_tag :defaults %>
<%= javascript_include_tag "jquery.minicolors.simple_form" %>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>

<style type="text/css">
  <% Quelle.all.each do |q| %>
    option.farbe<%= q.id %>  {
        color: #<%= q.farbe %>;
        background-color: #ffffff;
    }
  <% end %>
</style>
<%= form_for(@diagramm, :html => {:name => "qual_der_wahl", :onsubmit => "MarkiereErgebnisse()"}) do |f| %>
<!-- Errormessages Ausblenden wenn leer -->
  <% if @diagramm.errors.full_messages != []%>
    <%= @diagramm.errors.full_messages %>
  <%end%>
  
 <div class="card light-green lighten-5" style="margin: 1%;">
    <ul class="collapsible" data-collapsible="expandable">
        <li>
          <div class="collapsible-header active"><i class="material-icons">filter_drama</i>Name und Beschreibung des Diagrammes</div>
          <div class="collapsible-body">
            <div class="row">
              <div class="col s3">                  
                <%= f.label :name %><br />
                <%= f.text_field :name %><BR>
              </div>
              <div class="col s9">
                <%= f.label :beschreibung %><br />
                <%= f.text_field :beschreibung,:cols=>50,:rows=>3 %>
              </div>
            </div>
          </div>
        </li>
        <li>
          <div class="collapsible-header active"><i class="material-icons">filter_drama</i>Wahl der darzustellenden Messgr&ouml;&szlig;en</div>
          <div class="collapsible-body" height="50%">
            <div class="row">
              <div class="col s6">  
              <B>Deaktiviert</B>                
              </div>
              <div class="col s6">
              <B>Akiviert</B>
              </div>
            </div>
            <DIV id="quellen_auswahl_listen">
              <%= render :partial => "quellen_auswahl_listen" %>
            </DIV>
          </div>
        </li>
    </ul>
</div>
<!--%= submit_tag("Abbrechen", { :name => 'reset', :id => 'reset_button', :type => "reset",:onclick=>"window.location.reload()"}) %-->
<% end %>

app/views/diagramme/_zeit_navigation.html.erb
<div id="zeit_navigation">
  <TABLE width="100%">
    <TR>
      <TD align="center">
        <% dauern = navi_dauern(session[:akt_zeit]) %>
        <% dauern.each do |dauer| %>

            <% if session[:akt_zeit].dauer == dauer then %>
              <font size="+2"> &nbsp; <%= session[:akt_zeit].lesbar %> &nbsp; </font>
            <% elsif dauer.nil? then %>
              &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
            <% else %>
              &nbsp; <%= link_to dauer_lesbar(dauer), :remote=>true, :url => url_for({ :action => "dauer", :id => params[:id], :dauer => dauer, :format => "js" }) %> &nbsp;
          <% end %>
        <% end %>
      </TD>
      <TD valign="top" width="10%" align="right">
      </TD>
      <TD  valign="top" width="30%"  align="center">
        <%= link_to image_tag("arrow_left3.png",  :class => "navi_button"), :remote=>true, :url => url_for({ :action => "links", :id => params[:id], :format => "js" }) %> <!--edit_kurve_path(@kurve) % | -->
        <%= link_to image_tag("arrow_right3.png", :alt => 'nach rechts',  :class => "navi_button"), :remote=>true, :url => url_for({ :action => "rechts", :id => params[:id], :format => "js" }) %>
      </TD>
      <TD WIDTH="5%">
      </TD>
    </TR>
  </TABLE>
</div>

app/views/diagramme/edit.html.erb
<h1>Diagramm bearbeiten</h1>

<%= render :partial => "quellen_selektor" %>
<p>
<%= link_to raw(" <- Zur&uuml;ck zur Diagrammliste "), {:controller => :diagramme, :action => :index}%>
</p>

app/views/diagramme/grafik_aktualisierer.js.erb
//document.body.childNodes[17].firstChild.textContent = ("<>%= @highchart.series_data[0][:data].inspect %>");
//neu_json = '<%=raw @highchart.series_data.to_json %>';
//neu_json = '<%=raw @highchart.to_json %>';
//alert(neu_json);
//$("#fehlerausgabe_div").html(" <b>ok" +  "</b>");// json: " + neu_json);
/*
try{
  <%= raw high_chart("div_diagramm_neu", @highchart).gsub(/<[^<>]+>/,'') %>
    chart_quelle = window.chart_div_diagramm_neu;
    document.getElementById('div_diagramm_neu').style.visibility = 'hidden'; 
    //alert( $("#div_diagramm_neu" ) );
    //.style.visibility = 'hidden'; 
    chart_ziel = window.chart_div_diagramm;
    chart_ziel.series[0].setData(chart_quelle.series[0].yData, true);

    //chart_ziel.series[0].pointStart = chart_quelle.series[0].pointStart, true);
//  neue_daten = JSON.parse( neu_json );
} catch(e) {
  alert(e);
  $("#fehlerausgabe_div").html("Fehler: <b>" + e + "</b>");
}
*/
//chart = window.chart_div_diagramm;
/*
try {
  for (index = 0; index < neue_daten.length; index++) {
    //chart.series[index].setData(neue_daten[index]["data"], false);
    window.chart_div_diagramm = new HighCharts.Chart( neue_daten );
  }    
} catch(e) {
  $("#fehlerausgabe_div").html("Fehler beim Ersetzen: <b>" + e + "</b> json: " + neu_json);	
}
*/
//window.chart_div_diagramm.redraw();
//chart.redraw();

try {
  $("#aktuelle_zeit").html("<%= j(render('aktuelle_zeit')) %>");
} catch(e) {
  $("#fehlerausgabe_div").html("Fehler beim Zeit-Aktualisieren: <b>" + e + "</b>");
}

try{
    json_obj = '<%=  erg=(@highchart.to_json); raw(erg) %>';
    neue_daten = JSON.parse( json_obj );
    chart_ziel = window.chart_div_diagramm;
    var len_anfang = chart_ziel.series.length;
    if (neue_daten.options.y_axis.length < chart_ziel.yAxis.length){
      chart_ziel.yAxis[chart_ziel.yAxis.length-1].remove();
    }
    if (neue_daten.options.y_axis.length > chart_ziel.yAxis.length){
      chart_ziel.addAxis({}, false); //keine xAchse
    }
    for (var i = 0; i < neue_daten.options.y_axis.length; i++) {
      chart_ziel.yAxis[i].update({
        labels:     neue_daten.options.y_axis[i].labels,
        min:        neue_daten.options.y_axis[i].min,
        max:        neue_daten.options.y_axis[i].max,
        title:      neue_daten.options.y_axis[i].title,
        opposite:   neue_daten.options.y_axis[i].opposite
      }, false);
    }
    var len_vorher = chart_ziel.series.length;
    if (neue_daten.series_data.length < chart_ziel.series.length){
      chart_ziel.series[chart_ziel.series.length-1].remove();
    }
    while (neue_daten.series_data.length > chart_ziel.series.length){
      chart_ziel.addSeries({});
    }
    var len_nachher = chart_ziel.series.length;
    //$("#debugausgabe_series_div").html("Linie: <b>" + JSON.stringify(neue_daten) + "</b>");
    //$("#kurz_debug_div").html("<b> a:" + len_anfang + "  v:" + len_vorher + " n: " + len_nachher + "</b>");
    for (var i = 0; i < neue_daten.series_data.length; i++) {
      //$("#kurz_debug_div").append( "<br> i: " + i +  " l: " + chart_ziel.series.length + "");
      chart_ziel.series[i].update({
        data:         neue_daten.series_data[i]["data"],
        pointStart:   neue_daten.series_data[i].point_start,
        pointInterval:   neue_daten.series_data[i].point_interval,
        color:        neue_daten.series_data[i].color,
        name:         neue_daten.series_data[i].name,
        yAxis:        neue_daten.series_data[i].y_axis
      }, false);
      
    }
    chart_ziel.redraw();
} catch(e) {
  alert(e);
  $("#fehlerausgabe_div").html("Fehler: <b>" + e + "</b>");
}



  

app/views/diagramme/index.html.erb
<h1 style="text-align: center;">Diagramm-Liste <i class="material-icons medium">trending_up</i></h1>

<TABLE class="striped">
  <thead>
    <TR class="listenkopf">
      <th>Name </th>
      <th> Messgr&ouml;&szlig;en </th>
       <% if session[:expert_modus] then %>
      <th> &nbsp; </th>
      <th> &nbsp; </th>
      <% end %>
      <th> Beschreibung </th>
    </TR>
  </thead>
<% for diagramm in @diagramme %>
  <tr  class="<%= cycle('', 'un') + 'gerade'%>">
    <td  ><%= link_to diagramm.name, showfix_path(diagramm) %></td>
    <!--td  ><%=h diagramm.quellen.map(&:name).join(', ')%></td-->
    <td  ><%=raw diagramm.quellen.map{|q| ("<font color=\"##{q.farbe}\">#{q.name}</font>")}.join(', ')%></td>
    <% if session[:expert_modus] then %>
      <td  ><%= link_to 'bearbeiten', edit_diagramm_path(diagramm) %></td>
      <td  ><%= link_to raw('l&ouml;schen'), diagramm, :confirm => raw('Wollen Sie wirklich L&ouml;schen? Dann klicken Sie auf OK'), :method => :delete %></td>
    <% end %>
     <td ><%=h diagramm.beschreibung %></td>
 </tr>
<% end %>
</TABLE>

<br>
<% if session[:expert_modus] then %>
<%= link_to 'Neues Diagramm', new_diagramm_path %>
<% end %>

app/views/diagramme/new.html.erb
<h1>Neues Diagramm</h1>

<% form_for(@diagramm, :html => {:name => "qual_der_wahl", :onsubmit => "MarkiereErgebnisse()"}) do |f| %>
  <%= f.error_messages %>

<TABLE width="66%">
  <TR>
    <TD width="33%" VAlign="top">
    <%= f.label :name %><br />
    <%= f.text_field :name %><BR>
    </TD>
    <TD width="66%" VAlign="top">
     <%= f.label :beschreibung %><br />
    <%= f.text_field :beschreibung,:cols=>50,:rows=>3 %>
    </TD>
  </TR>
</TABLE>
<br>
<%= f.submit "Erstellen" %>

<%= link_to raw('Zur&uuml;ck'), diagramme_path %>


<% end %>

app/views/diagramme/show.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<%= javascript_include_tag :all %>
<!--script type="text/javascript" src="/javascripts/swfobject.js"></script-->

<!--%= javascript_include_tag "javascripts/highcharts/highcharts.js", "chartkick" %-->
<!--%= javascript_include_tag "highcharts", "chartkick" %-->
<!--%= column_chart  name: 'test', data: [1,43,77,55,66,23,77,65] %-->
<!--%= column_chart  name: 17, data: 22 %-->

<div id="fehlerausgabe_div">
</div>
<div id="debugausgabe_series_div">
</div>
<div id="debugausgabe_y_axis_div">
</div>
<div id="grafik_container">
  <%= render :partial => "grafik" %>
</div>

<!--%= link_to "open", {}, :target => "_blank" %-->
<!--%= button_to_function 'Save', "window.blur();" %-->
<!--%= button_to_function 'Save', "self.close();" %-->

<% if session[:expert_modus] %>
  <%= render :partial => "quellen_selektor" %>
<% else %>
  <%= link_to " Diagramm-Auswahl", {:controller => :diagramme, :action => :index} %>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%=h @diagramm.beschreibung %>
<% end %>